### ISSUE TITLE
Dependency problem with faraday 1.0.0

### ISSUE THREAD

**Issue by jlavanchy** [Azure/azure-ruby-asm-core#70]
Hello, 

We are using Chef, and the gem azure-core to access and download resources from Azure blob. The last version of Chef (15.8.23) ship with Faraday 1.0.0 which has been released in January. 

The gem azure-core has a dependency on Faraday ~> 0.9. Which breaks the last version of Chef in our case because of this dependency. 

Could you please review and try to fix this issue? 

Thanks in advance! 

Regards, Julien.

**Comment by yaxia** [comment]
@jlavanchy, may I understand more on how you download resource from Azure blob? Do you use azure-core directly or use the azure-storage-ruby which depends on azure-core?
I ask because this repo is not actively maintained and we have a plan to move the functionalities of this repo to azure-storage-ruby and maintain upgrades there.

**Comment by jlavanchy** [comment]
Hello, 

We are using azure-storage-blob gem as well as azure-storage-common gem which are both using azure-core to work.

**Comment by jlavanchy** [comment]
I will report the issue to the main azure-storage-ruby since we are using mainly azure-storage-blob, which depends on azure-core gems.

**Comment by jlavanchy** [comment]
This was resolve in https://github.com/Azure/azure-storage-ruby/issues/154. Closing the issue.
